name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why?
      description: How would this help pet owners?
    validations:
      required: false
